Traceback (most recent call last):
  File "/home/kashyap/.virtualenvs/eme/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/kashyap/.virtualenvs/eme/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/kashyap/.virtualenvs/eme/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/kashyap/.virtualenvs/eme/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/kashyap/.virtualenvs/eme/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/kashyap/.virtualenvs/eme/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/kashyap/.virtualenvs/eme/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import logomaker
import matplotlib.pyplot as plt
import seaborn as sns

from collections import Counter
sns.set_context("notebook", font_scale=1.5)

import tarfile
import pickle

from collections import defaultdict
from eme.sequence import canonical

subsample = "full"
k = 5

tar = tarfile.open(f"data/results_{subsample}_k_5_10.tar.xz", "r:xz")
with tar.extractfile(f"results_{k}.bz2") as iH:
    counts = pickle.load(iH)
    _fractions = pickle.load(iH)
    models = pickle.load(iH)
tar.close()

melt_fractions_mean = pd.read_csv("data/melt_fractions_mean.tsv", sep="\t")
df = pd.read_csv("data/metadata.tsv", sep="\t", index_col=7)

def get_logo_mean(models, samples, kmer):
  kmer_pfm = Counter()
  for s in samples:
      kmer_pfm.update(models[s][kmer])
  kmer_ppm = logomaker.transform_matrix(pd.DataFrame.from_dict(kmer_pfm).T, from_type='counts',
                             to_type="probability")
  return kmer_ppm

fig, axes = plt.subplots(2, 3, figsize=(10, 5))
for (i, j), ax in zip(melt_fractions_mean[(melt_fractions_mean["protein"]=="ZFC4") & (melt_fractions_mean["cycle"]==6)][["cycle", "protein", "kmer", "AT", "value"]].sort_values(
  by="value", ascending=False).head(6).iterrows(), axes.flatten()):
    cycle, protein, kmer, at, fraction = j.values
    samples = list(df[(df["protein"]==protein) & (df["cycle"]==cycle)].index)    
    kmer_ppm = get_logo_mean(models, samples, kmer)
    logomaker.Logo(kmer_ppm, ax=ax)
    ax.set_title(f"{kmer}\nabundance={fraction:.2f}")
_ = fig.tight_layout()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/tmp/ipykernel_34352/3507055169.py[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0mk[0m [0;34m=[0m [0;36m5[0m[0;34m[0m[0;34m[0m[0m
[1;32m     17[0m [0;34m[0m[0m
[0;32m---> 18[0;31m [0mtar[0m [0;34m=[0m [0mtarfile[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0;34mf"data/results_{subsample}_k_5_10.tar.xz"[0m[0;34m,[0m [0;34m"r:xz"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     19[0m [0;32mwith[0m [0mtar[0m[0;34m.[0m[0mextractfile[0m[0;34m([0m[0;34mf"results_{k}.bz2"[0m[0;34m)[0m [0;32mas[0m [0miH[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     20[0m     [0mcounts[0m [0;34m=[0m [0mpickle[0m[0;34m.[0m[0mload[0m[0;34m([0m[0miH[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.10/tarfile.py[0m in [0;36mopen[0;34m(cls, name, mode, fileobj, bufsize, **kwargs)[0m
[1;32m   1631[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1632[0m                 [0;32mraise[0m [0mCompressionError[0m[0;34m([0m[0;34m"unknown compression type %r"[0m [0;34m%[0m [0mcomptype[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1633[0;31m             [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0mname[0m[0;34m,[0m [0mfilemode[0m[0;34m,[0m [0mfileobj[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1634[0m [0;34m[0m[0m
[1;32m   1635[0m         [0;32melif[0m [0;34m"|"[0m [0;32min[0m [0mmode[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.10/tarfile.py[0m in [0;36mxzopen[0;34m(cls, name, mode, fileobj, preset, **kwargs)[0m
[1;32m   1737[0m             [0;32mraise[0m [0mCompressionError[0m[0;34m([0m[0;34m"lzma module is not available"[0m[0;34m)[0m [0;32mfrom[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1738[0m [0;34m[0m[0m
[0;32m-> 1739[0;31m         [0mfileobj[0m [0;34m=[0m [0mLZMAFile[0m[0;34m([0m[0mfileobj[0m [0;32mor[0m [0mname[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0mpreset[0m[0;34m=[0m[0mpreset[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1740[0m [0;34m[0m[0m
[1;32m   1741[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.10/lzma.py[0m in [0;36m__init__[0;34m(self, filename, mode, format, check, preset, filters)[0m
[1;32m    118[0m             [0;32mif[0m [0;34m"b"[0m [0;32mnot[0m [0;32min[0m [0mmode[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    119[0m                 [0mmode[0m [0;34m+=[0m [0;34m"b"[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 120[0;31m             [0mself[0m[0;34m.[0m[0m_fp[0m [0;34m=[0m [0mbuiltins[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    121[0m             [0mself[0m[0;34m.[0m[0m_closefp[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m
[1;32m    122[0m             [0mself[0m[0;34m.[0m[0m_mode[0m [0;34m=[0m [0mmode_code[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/results_full_k_5_10.tar.xz'
FileNotFoundError: [Errno 2] No such file or directory: 'data/results_full_k_5_10.tar.xz'

